// Mocks generated by Mockito 5.4.4 from annotations
// in task_manager_app/test/cubits/login_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:task_manager_app/core/networks/failures.dart' as _i5;
import 'package:task_manager_app/models/refresh_auth_session_model.dart' as _i7;
import 'package:task_manager_app/models/user_data_model.dart' as _i6;
import 'package:task_manager_app/repositories/auth_repo/auth_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i3.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserDataModel>> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserDataModel>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserDataModel>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #username: username,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserDataModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserDataModel>> getCurrentUserData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserData,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UserDataModel>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserDataModel>(
          this,
          Invocation.method(
            #getCurrentUserData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserDataModel>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i7.RefreshAuthSessionModel>> refreshAuthSession(
          {required String? refreshToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshAuthSession,
          [],
          {#refreshToken: refreshToken},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i7.RefreshAuthSessionModel>>.value(
            _FakeEither_0<_i5.Failure, _i7.RefreshAuthSessionModel>(
          this,
          Invocation.method(
            #refreshAuthSession,
            [],
            {#refreshToken: refreshToken},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.RefreshAuthSessionModel>>);
}
